USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS BENCH2COST_MEDIUM
  WAREHOUSE_SIZE = MEDIUM
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE IF NOT EXISTS BENCH2COST_4XLARGE
  WAREHOUSE_SIZE = '4X-LARGE'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;