USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS BENCH2COST_MEDIUM
  WAREHOUSE_SIZE = MEDIUM
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;


CREATE WAREHOUSE IF NOT EXISTS BENCH2COST_MEDIUM_GEN2
  WAREHOUSE_SIZE = MEDIUM
  GENERATION = '2'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE IF NOT EXISTS BENCH2COST_LARGE
  WAREHOUSE_SIZE = LARGE
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE IF NOT EXISTS BENCH2COST_LARGE_GEN2
  WAREHOUSE_SIZE = LARGE
  GENERATION = '2'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;



CREATE WAREHOUSE IF NOT EXISTS BENCH2COST_4XLARGE
  WAREHOUSE_SIZE = '4X-LARGE'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE IF NOT EXISTS BENCH2COST_4XLARGE_GEN2
  WAREHOUSE_SIZE = '4X-LARGE'
  GENERATION = '2'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;